### ISSUE TITLE
Sales Order includes deleted rows

### ISSUE THREAD

**Issue by UtahGooner** [UtahGooner/api-sales#2]
When loading a Sales Order it shows the deleted rows still when loaded from the SO_SalesOrderHistoryDetail

Page: https://intranet.chums.com/reports/account/salesorder/
Example: see https://intranet.chums.com/reports/account/salesorder/?company=CHI&salesorderno=0280268
Bug: deleted rows still show, perhaps can be filtered with excluding rows where `QuantityOrdered === 0`
API Path: https://intranet.chums.com/api/sales/orders/chums/0280268

![Image](https://github.com/user-attachments/assets/530fda4a-a17f-4800-a8a9-bbb1f7f0f339)

**Comment by mgchums** [comment]
Query edited to filter QuantityOrderedRevised <> 0
